In [1]:
import numpy as np
import pandas as pd

In [2]:
# M1 = accretor
# M2 = donor
# q = M2/M1

In [3]:
columns = [
    "System Name", "RA", "Dec", "Period", "Eccentricity",
    "M1", "M2", "q", "Mass Function",
    "Type1", "Type2", "Detection Method", "Reference", "Notes"
]
observations_df = pd.DataFrame(columns=columns)

In [4]:
from astroquery.simbad import Simbad

def get_ra_dec(star_name):
    # Customize Simbad to return RA and DEC in degrees
    Simbad.add_votable_fields('ra(d)', 'dec(d)')
    
    # Query Simbad
    result = Simbad.query_object(star_name)
    
    if result is None:
        print(f"Star '{star_name}' not found in SIMBAD.")
        return None, None

    ra = result['RA_d'][0]  # RA in degrees
    dec = result['DEC_d'][0]  # Dec in degrees

    return ra, dec

In [5]:
print(get_ra_dec('VFTS 291'))

(84.57383943733, -69.06070833548)

In [6]:
# VFTS 291

VFTS_291 = ['VFTS 291',
                [np.nan, 84.57383943733, np.nan], [np.nan, -69.06070833548, np.nan],  # RA and Dec in degrees
                [0.038, 108.062, 0.038],  # Period in days
                [np.nan, 0, np.nan],  # Eccentricity
                [1.5, 13.2, 1.5],  # M1 in solar masses
                [1.5, 2.0, 2.5],  # M2 in solar masses
                [np.nan, np.nan, np.nan],  # q
                [0.067, 9.197, 0.067],  # Mass Function in solar masses
                'B', 'SS', ['RV'], '2023MNRAS.525.5121V', 'Inflated SS + early B star in LMC']

observations_df.loc[len(observations_df)] = VFTS_291

In [7]:
print(get_ra_dec('LB 1'))

(183.1603404719799, 26.63651808279)

In [8]:
# LB-1

LB_1 = ['LB-1',
                [np.nan, 183.1603404719799, np.nan], [np.nan, 26.63651808279, np.nan],  # RA and Dec in degrees
                [0.0097, 78.7999 , 0.0097],  # Period in days
                [np.nan, 0, np.nan],  # Eccentricity
                [2, 7, 2],  # M1 in solar masses
                [0.4, 1.5, 0.4],  # M2 in solar masses
                [0.02, 0.21, 0.02],  # q
                [np.nan, np.nan, np.nan],  # Mass Function in solar masses
                'B3Ve', 'SS', ['RV'], '2020A&A...639L...6S', 'Galactic BH impostor']

observations_df.loc[len(observations_df)] = LB_1

In [9]:
print(get_ra_dec('NGC 1850 BH1'))

(77.19458, -68.76544)

In [10]:
# NGC 1850 BH1

NGC_1850_BH1 = ['NGC 1850 BH1',
                [np.nan, 77.19458, np.nan], [np.nan, -68.76544, np.nan],  # RA and Dec in degrees
                [np.nan, 5.04, np.nan],  # Period in days
                [np.nan, 0, np.nan],  # Eccentricity
                [2.5, 10.0, 2.5],  # M1 in solar masses
                [1.25, 3.75, 1.25],  # M2 in solar masses
                [np.nan, np.nan, np.nan],  # q
                [np.nan, np.nan, np.nan],  # Mass Function in solar masses
                'MS', 'SS', ['RV'], '2022MNRAS.511L..24E', 'LMC BH impostor']

observations_df.loc[len(observations_df)] = NGC_1850_BH1

In [11]:
print(get_ra_dec('HR 6819'))

(274.2813851056508, -56.0233493287564)

In [12]:
# HR 6819

HR_6819 = ['HR 6819',
                [np.nan, 274.2813851056508, np.nan], [np.nan, -56.0233493287564, np.nan],  # RA and Dec in degrees
                [0.112, 40.335, 0.112],  # Period in days
                [np.nan, 0, np.nan],  # Eccentricity
                [3, 6, 5],  # M1 in solar masses
                [0.1, 0.4, 0.3],  # M2 in solar masses
                [0.0133, 0.0667, 0.0133],  # q
                [np.nan, np.nan, np.nan],  # Mass Function in solar masses
                'B2-3Ve', 'SS', ['RV'], '2020A&A...641A..43B', 'Galactic BH impostor']

observations_df.loc[len(observations_df)] = HR_6819

In [13]:
print(get_ra_dec('2dFS 163'))

(9.2426590985, -73.39254642784)

In [14]:
# 2dFS 163

_2dFS_163 = ['2dFS 163',
                [np.nan, 9.2426590985, np.nan], [np.nan, -73.39254642784, np.nan],  # RA and Dec in degrees
                [np.nan, np.nan, np.nan],  # Period in days
                [np.nan, np.nan, np.nan],  # Eccentricity
                [4, 10.5, 5],  # M1 in solar masses
                [1.5, 3.96, 1.8],  # M2 in solar masses
                [np.nan, np.nan, np.nan],  # q
                [np.nan, np.nan, np.nan],  # Mass Function in
                'B0-1Ve', 'SS', ['RV'], '2024A&A...692A..90R', 'Partial SS star in SMC']

observations_df.loc[len(observations_df)] = _2dFS_163

In [15]:
print(get_ra_dec('2dFS 2553'))

(17.34145496677, -73.26164308599)

In [16]:
# 2dFS 2553

_2dFS_2553 = ['2dFS 2553',
                [np.nan, 17.34145496677, np.nan], [np.nan, -73.26164308599, np.nan],  # RA and Dec in degrees
                [0.08, 93.6, 0.07],  # Period in days
                [np.nan, 0.03, np.nan],  # Eccentricity
                [3.5, 13.8, 5],  # M1 in solar masses
                [2.8, 6.86, 3.3],  # M2 in solar masses
                [0.540, 0.769, 0.943],  # q
                [np.nan, np.nan, np.nan],  # Mass Function in solar masses
                'Be', 'SS', ['RV'], '2024A&A...692A..90R', 'Partial SS in SMC']

observations_df.loc[len(observations_df)] = _2dFS_2553

In [17]:
print(get_ra_dec('Sk -71 35'))

(82.51740448754, -71.13228988849)

In [18]:
# Sk -71â—¦ 35

Sk_71_35 = ['Sk -71 35',
                [np.nan, 82.51740448754, np.nan], [np.nan, -71.13228988849, np.nan],  # RA and Dec in degrees
                [np.nan, 9.39864, np.nan],  # Period in days
                [np.nan, 0, np.nan],  # Eccentricity
                [14, 35.7, 18],  # M1 in solar masses
                [3, 7.8, 3.6],  # M2 in solar masses
                [0.4286, 0.3684, 0.5714],  # q
                [np.nan, np.nan, np.nan],  # Mass Function in solar masses
                'O9Ve', 'SS', ['RV'], '2024A&A...692A..90R', 'Partial SS star in LMC']

observations_df.loc[len(observations_df)] = Sk_71_35

In [19]:
print(get_ra_dec('SMCSGS-FS 69'))

(21.04495344579, -73.36942282166)

In [20]:
# SMCSGS-FS 69

SMCSGS_FS_69 = ['SMCSGS-FS 69',
                [np.nan, 21.04495344579, np.nan], [np.nan, -73.36942282166, np.nan],  # RA and Dec in degrees
                [np.nan, np.nan, np.nan],  # Period in days
                [np.nan, np.nan, np.nan],  # Eccentricity
                [7, 17, 9],  # M1 in solar masses
                [0.8, 2.8, 1.5],  # M2 in solar masses
                [np.nan, np.nan, np.nan],  # q
                [np.nan, np.nan, np.nan],  # Mass Function in solar masses
                'Be', 'SS', ['RV'], '2023A&A...674L..12R', 'Partial SS star in SMC']

observations_df.loc[len(observations_df)] = SMCSGS_FS_69

In [21]:
print(get_ra_dec('Gamma Columbae'))

(89.3842085692467, -35.2832809864814)

In [22]:
# Gamma Columbae

Gamma_Columbae = ['Gamma Columbae',
                [np.nan, 89.3842085692467, np.nan], [np.nan, -35.2832809864814, np.nan],  # RA and Dec in degrees
                [np.nan, np.nan, np.nan],  # Period in days
                [np.nan, np.nan, np.nan],  # Eccentricity
                [np.nan, np.nan, np.nan],  # M1 in solar masses
                [.5, 4.5, .5],  # M2 in solar masses
                [np.nan, np.nan, np.nan],  # q
                [np.nan, np.nan, np.nan],  # Mass Function in solar masses
                '?', 'SS', ['RV'], '2022NatAs...6.1414I', 'Galactic inflated SS star']

observations_df.loc[len(observations_df)] = Gamma_Columbae

In [23]:
print(get_ra_dec('Upsilon Sagittarii'))

(290.4317608155338, -15.9550174239706)

In [24]:
# Upsilon Sgr

Upsilon_Sagittarii = ['Upsilon Sagittarii',
                [np.nan, 290.4317608155338, np.nan], [np.nan, -15.9550174239706, np.nan],  # RA and Dec in degrees
                [np.nan, 137.9343, np.nan],  # Period in days
                [np.nan, 0, np.nan],  # Eccentricity
                [0.8, 6.8, 0.8],  # M1 in solar masses
                [0.2, 0.3, 0.5],  # M2 in solar masses
                [np.nan, np.nan, np.nan],  # q
                [np.nan, np.nan, np.nan],  # Mass Function in solar masses
                'B', 'SS', ['RV'], '2023MNRAS.518.3541G', 'Galactic He supergiant']

observations_df.loc[len(observations_df)] = Upsilon_Sagittarii
observations_df

,System Name,RA,Dec,Period,Eccentricity,M1,M2,q,Mass Function,Type1,Type2,Detection Method,Reference,Notes
0,VFTS 291,"[nan, 84.57383943733, nan]","[nan, -69.06070833548, nan]","[0.038, 108.062, 0.038]","[nan, 0, nan]","[1.5, 13.2, 1.5]","[1.5, 2.0, 2.5]","[nan, nan, nan]","[0.067, 9.197, 0.067]",B,SS,[RV],2023MNRAS.525.5121V,Inflated SS + early B star in LMC
1,LB-1,"[nan, 183.1603404719799, nan]","[nan, 26.63651808279, nan]","[0.0097, 78.7999, 0.0097]","[nan, 0, nan]","[2, 7, 2]","[0.4, 1.5, 0.4]","[0.02, 0.21, 0.02]","[nan, nan, nan]",B3Ve,SS,[RV],2020A&A...639L...6S,Galactic BH impostor
2,NGC 1850 BH1,"[nan, 77.19458, nan]","[nan, -68.76544, nan]","[nan, 5.04, nan]","[nan, 0, nan]","[2.5, 10.0, 2.5]","[1.25, 3.75, 1.25]","[nan, nan, nan]","[nan, nan, nan]",MS,SS,[RV],2022MNRAS.511L..24E,LMC BH impostor
3,HR 6819,"[nan, 274.2813851056508, nan]","[nan, -56.0233493287564, nan]","[0.112, 40.335, 0.112]","[nan, 0, nan]","[3, 6, 5]","[0.1, 0.4, 0.3]","[0.0133, 0.0667, 0.0133]","[nan, nan, nan]",B2-3Ve,SS,[RV],2020A&A...641A..43B,Galactic BH impostor
4,2dFS 163,"[nan, 9.2426590985, nan]","[nan, -73.39254642784, nan]","[nan, nan, nan]","[nan, nan, nan]","[4, 10.5, 5]","[1.5, 3.96, 1.8]","[nan, nan, nan]","[nan, nan, nan]",B0-1Ve,SS,[RV],2024A&A...692A..90R,Partial SS star in SMC
5,2dFS 2553,"[nan, 17.34145496677, nan]","[nan, -73.26164308599, nan]","[0.08, 93.6, 0.07]","[nan, 0.03, nan]","[3.5, 13.8, 5]","[2.8, 6.86, 3.3]","[0.54, 0.769, 0.943]","[nan, nan, nan]",Be,SS,[RV],2024A&A...692A..90R,Partial SS in SMC
6,Sk -71 35,"[nan, 82.51740448754, nan]","[nan, -71.13228988849, nan]","[nan, 9.39864, nan]","[nan, 0, nan]","[14, 35.7, 18]","[3, 7.8, 3.6]","[0.4286, 0.3684, 0.5714]","[nan, nan, nan]",O9Ve,SS,[RV],2024A&A...692A..90R,Partial SS star in LMC
7,SMCSGS-FS 69,"[nan, 21.04495344579, nan]","[nan, -73.36942282166, nan]","[nan, nan, nan]","[nan, nan, nan]","[7, 17, 9]","[0.8, 2.8, 1.5]","[nan, nan, nan]","[nan, nan, nan]",Be,SS,[RV],2023A&A...674L..12R,Partial SS star in SMC
8,Gamma Columbae,"[nan, 89.3842085692467, nan]","[nan, -35.2832809864814, nan]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]","[0.5, 4.5, 0.5]","[nan, nan, nan]","[nan, nan, nan]",?,SS,[RV],2022NatAs...6.1414I,Galactic inflated SS star
9,Upsilon Sagittarii,"[nan, 290.4317608155338, nan]","[nan, -15.9550174239706, nan]","[nan, 137.9343, nan]","[nan, 0, nan]","[0.8, 6.8, 0.8]","[0.2, 0.3, 0.5]","[nan, nan, nan]","[nan, nan, nan]",B,SS,[RV],2023MNRAS.518.3541G,Galactic He supergiant

## Format table correctly

In [25]:
# Define columns, with key quantities stored as lists: [err-, value, err+]
columns = [
    "System Name", "RA", "Dec", "Period", "Eccentricity",
    "M1","M1_sin3i", "M2", "M2_sin3i", "q", "Mass Function",
    "Type1", "Type2", "Detection Method", "Reference", "Notes"
]


# Initialize empty DataFrame
stripped_star_table = pd.DataFrame(columns=columns)
stripped_star_table

Empty DataFrame
Columns: [System Name, RA, Dec, Period, Eccentricity, M1, M1_sin3i, M2, M2_sin3i, q, Mass Function, Type1, Type2, Detection Method, Reference, Notes]
Index: []

In [26]:
stripped_star_table['System Name'] = observations_df['System Name']
stripped_star_table['RA'] = observations_df['RA']
stripped_star_table['Dec'] = observations_df['Dec']
stripped_star_table['Period'] = observations_df['Period']
stripped_star_table['Eccentricity'] = observations_df['Eccentricity']
stripped_star_table['M1'] = observations_df['M1']
stripped_star_table['M1_sin3i'] = [[np.nan, np.nan, np.nan] for _ in observations_df['M1']]
stripped_star_table['M2'] = observations_df['M2']
stripped_star_table['M2_sin3i'] = [[np.nan, np.nan, np.nan] for _ in observations_df['M2']]
stripped_star_table['q'] = observations_df['q']
stripped_star_table['Mass Function'] = observations_df['Mass Function']
stripped_star_table['Type1'] = observations_df['Type1']
stripped_star_table['Type2'] = observations_df['Type2']
stripped_star_table['Detection Method'] = observations_df['Detection Method']
stripped_star_table['Reference'] = [[ref] for ref in observations_df['Reference']]
stripped_star_table['Notes'] = observations_df['Notes']
stripped_star_table

,System Name,RA,Dec,Period,Eccentricity,M1,M1_sin3i,M2,M2_sin3i,q,Mass Function,Type1,Type2,Detection Method,Reference,Notes
0,VFTS 291,"[nan, 84.57383943733, nan]","[nan, -69.06070833548, nan]","[0.038, 108.062, 0.038]","[nan, 0, nan]","[1.5, 13.2, 1.5]","[nan, nan, nan]","[1.5, 2.0, 2.5]","[nan, nan, nan]","[nan, nan, nan]","[0.067, 9.197, 0.067]",B,SS,[RV],[2023MNRAS.525.5121V],Inflated SS + early B star in LMC
1,LB-1,"[nan, 183.1603404719799, nan]","[nan, 26.63651808279, nan]","[0.0097, 78.7999, 0.0097]","[nan, 0, nan]","[2, 7, 2]","[nan, nan, nan]","[0.4, 1.5, 0.4]","[nan, nan, nan]","[0.02, 0.21, 0.02]","[nan, nan, nan]",B3Ve,SS,[RV],[2020A&A...639L...6S],Galactic BH impostor
2,NGC 1850 BH1,"[nan, 77.19458, nan]","[nan, -68.76544, nan]","[nan, 5.04, nan]","[nan, 0, nan]","[2.5, 10.0, 2.5]","[nan, nan, nan]","[1.25, 3.75, 1.25]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]",MS,SS,[RV],[2022MNRAS.511L..24E],LMC BH impostor
3,HR 6819,"[nan, 274.2813851056508, nan]","[nan, -56.0233493287564, nan]","[0.112, 40.335, 0.112]","[nan, 0, nan]","[3, 6, 5]","[nan, nan, nan]","[0.1, 0.4, 0.3]","[nan, nan, nan]","[0.0133, 0.0667, 0.0133]","[nan, nan, nan]",B2-3Ve,SS,[RV],[2020A&A...641A..43B],Galactic BH impostor
4,2dFS 163,"[nan, 9.2426590985, nan]","[nan, -73.39254642784, nan]","[nan, nan, nan]","[nan, nan, nan]","[4, 10.5, 5]","[nan, nan, nan]","[1.5, 3.96, 1.8]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]",B0-1Ve,SS,[RV],[2024A&A...692A..90R],Partial SS star in SMC
5,2dFS 2553,"[nan, 17.34145496677, nan]","[nan, -73.26164308599, nan]","[0.08, 93.6, 0.07]","[nan, 0.03, nan]","[3.5, 13.8, 5]","[nan, nan, nan]","[2.8, 6.86, 3.3]","[nan, nan, nan]","[0.54, 0.769, 0.943]","[nan, nan, nan]",Be,SS,[RV],[2024A&A...692A..90R],Partial SS in SMC
6,Sk -71 35,"[nan, 82.51740448754, nan]","[nan, -71.13228988849, nan]","[nan, 9.39864, nan]","[nan, 0, nan]","[14, 35.7, 18]","[nan, nan, nan]","[3, 7.8, 3.6]","[nan, nan, nan]","[0.4286, 0.3684, 0.5714]","[nan, nan, nan]",O9Ve,SS,[RV],[2024A&A...692A..90R],Partial SS star in LMC
7,SMCSGS-FS 69,"[nan, 21.04495344579, nan]","[nan, -73.36942282166, nan]","[nan, nan, nan]","[nan, nan, nan]","[7, 17, 9]","[nan, nan, nan]","[0.8, 2.8, 1.5]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]",Be,SS,[RV],[2023A&A...674L..12R],Partial SS star in SMC
8,Gamma Columbae,"[nan, 89.3842085692467, nan]","[nan, -35.2832809864814, nan]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]","[0.5, 4.5, 0.5]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]",?,SS,[RV],[2022NatAs...6.1414I],Galactic inflated SS star
9,Upsilon Sagittarii,"[nan, 290.4317608155338, nan]","[nan, -15.9550174239706, nan]","[nan, 137.9343, nan]","[nan, 0, nan]","[0.8, 6.8, 0.8]","[nan, nan, nan]","[0.2, 0.3, 0.5]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]",B,SS,[RV],[2023MNRAS.518.3541G],Galactic He supergiant

In [27]:
# Extend the HDF5 saving function to include metadata
import h5py
def save_triplet_columns_and_metadata(df, triplet_columns, h5_filename):
    with h5py.File(h5_filename, "w") as f:
        # Save each triplet column as a dataset
        for col in triplet_columns:
            try:
                arr = np.vstack(df[col].values)  # Shape (N, 3)
                f.create_dataset(col, data=arr)
            except Exception as e:
                print(f"Skipping column '{col}' due to: {e}")
        
        # Save all other columns as metadata in JSON format
        metadata_cols = [col for col in df.columns if col not in triplet_columns]
        metadata_df = df[metadata_cols]

        # Convert to JSON-serializable format and store as a string
        meta_json = metadata_df.to_json(orient="records")
        f.create_dataset("metadata_json", data=np.bytes_(meta_json))

#

In [28]:
#  Run the function with metadata saving
triplet_cols = ["RA", "Dec", "Period", "Eccentricity", "M1", "M1_sin3i", "M2", "M2_sin3i", "q", "Mass Function"]
save_triplet_columns_and_metadata(stripped_star_table, triplet_cols, "../result_tables/stripped_star_table.h5")

In [29]:
stripped_star_table

,System Name,RA,Dec,Period,Eccentricity,M1,M1_sin3i,M2,M2_sin3i,q,Mass Function,Type1,Type2,Detection Method,Reference,Notes
0,VFTS 291,"[nan, 84.57383943733, nan]","[nan, -69.06070833548, nan]","[0.038, 108.062, 0.038]","[nan, 0, nan]","[1.5, 13.2, 1.5]","[nan, nan, nan]","[1.5, 2.0, 2.5]","[nan, nan, nan]","[nan, nan, nan]","[0.067, 9.197, 0.067]",B,SS,[RV],[2023MNRAS.525.5121V],Inflated SS + early B star in LMC
1,LB-1,"[nan, 183.1603404719799, nan]","[nan, 26.63651808279, nan]","[0.0097, 78.7999, 0.0097]","[nan, 0, nan]","[2, 7, 2]","[nan, nan, nan]","[0.4, 1.5, 0.4]","[nan, nan, nan]","[0.02, 0.21, 0.02]","[nan, nan, nan]",B3Ve,SS,[RV],[2020A&A...639L...6S],Galactic BH impostor
2,NGC 1850 BH1,"[nan, 77.19458, nan]","[nan, -68.76544, nan]","[nan, 5.04, nan]","[nan, 0, nan]","[2.5, 10.0, 2.5]","[nan, nan, nan]","[1.25, 3.75, 1.25]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]",MS,SS,[RV],[2022MNRAS.511L..24E],LMC BH impostor
3,HR 6819,"[nan, 274.2813851056508, nan]","[nan, -56.0233493287564, nan]","[0.112, 40.335, 0.112]","[nan, 0, nan]","[3, 6, 5]","[nan, nan, nan]","[0.1, 0.4, 0.3]","[nan, nan, nan]","[0.0133, 0.0667, 0.0133]","[nan, nan, nan]",B2-3Ve,SS,[RV],[2020A&A...641A..43B],Galactic BH impostor
4,2dFS 163,"[nan, 9.2426590985, nan]","[nan, -73.39254642784, nan]","[nan, nan, nan]","[nan, nan, nan]","[4, 10.5, 5]","[nan, nan, nan]","[1.5, 3.96, 1.8]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]",B0-1Ve,SS,[RV],[2024A&A...692A..90R],Partial SS star in SMC
5,2dFS 2553,"[nan, 17.34145496677, nan]","[nan, -73.26164308599, nan]","[0.08, 93.6, 0.07]","[nan, 0.03, nan]","[3.5, 13.8, 5]","[nan, nan, nan]","[2.8, 6.86, 3.3]","[nan, nan, nan]","[0.54, 0.769, 0.943]","[nan, nan, nan]",Be,SS,[RV],[2024A&A...692A..90R],Partial SS in SMC
6,Sk -71 35,"[nan, 82.51740448754, nan]","[nan, -71.13228988849, nan]","[nan, 9.39864, nan]","[nan, 0, nan]","[14, 35.7, 18]","[nan, nan, nan]","[3, 7.8, 3.6]","[nan, nan, nan]","[0.4286, 0.3684, 0.5714]","[nan, nan, nan]",O9Ve,SS,[RV],[2024A&A...692A..90R],Partial SS star in LMC
7,SMCSGS-FS 69,"[nan, 21.04495344579, nan]","[nan, -73.36942282166, nan]","[nan, nan, nan]","[nan, nan, nan]","[7, 17, 9]","[nan, nan, nan]","[0.8, 2.8, 1.5]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]",Be,SS,[RV],[2023A&A...674L..12R],Partial SS star in SMC
8,Gamma Columbae,"[nan, 89.3842085692467, nan]","[nan, -35.2832809864814, nan]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]","[0.5, 4.5, 0.5]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]",?,SS,[RV],[2022NatAs...6.1414I],Galactic inflated SS star
9,Upsilon Sagittarii,"[nan, 290.4317608155338, nan]","[nan, -15.9550174239706, nan]","[nan, 137.9343, nan]","[nan, 0, nan]","[0.8, 6.8, 0.8]","[nan, nan, nan]","[0.2, 0.3, 0.5]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]",B,SS,[RV],[2023MNRAS.518.3541G],Galactic He supergiant

In [30]:
#print(get_ra_dec('KS Persei'))

In [31]:
# KS Persei, to do!
'''
KS_Persei = ['KS Persei',
                [np.nan, 53.198, np.nan], [np.nan, 32.458, np.nan],  # RA and Dec in degrees
                [np.nan, 0.8, np.nan],  # Period in days
                [np.nan, 0, np.nan],  # Eccentricity
                [2.5, 6.5, 2.5],  # M1 in solar masses
                [0.4, 1.2, 0.4],  # M2 in solar masses
                [0.16, 0.18, 0.14],  # q
                [np.nan, np.nan, np.nan],  # Mass Function in solar masses
                'B', 'SS', ['RV'], '2023MNRAS.518.3541G', 'Galactic He supergiant']

observations_df.loc[len(observations_df)] = KS_Persei
observations_df
'''

"\nKS_Persei = ['KS Persei',\n                [np.nan, 53.198, np.nan], [np.nan, 32.458, np.nan],  # RA and Dec in degrees\n                [np.nan, 0.8, np.nan],  # Period in days\n                [np.nan, 0, np.nan],  # Eccentricity\n                [2.5, 6.5, 2.5],  # M1 in solar masses\n                [0.4, 1.2, 0.4],  # M2 in solar masses\n                [0.16, 0.18, 0.14],  # q\n                [np.nan, np.nan, np.nan],  # Mass Function in solar masses\n                'B', 'SS', ['RV'], '2023MNRAS.518.3541G', 'Galactic He supergiant']\n\nobservations_df.loc[len(observations_df)] = KS_Persei\nobservations_df\n"